channels:
  - mvdbeek
  - bioconda
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - apipkg=1.5
  - astroid=2.3.1
  - atomicwrites=1.3.0
  - attrs=19.1.0
  - backcall=0.1.0
  - bitstring=3.1.5
  - blas=1.0
  - bleach=3.1.0
  - ca-certificates=2019.11.28
  - cairo=1.14.12
  - certifi=2019.11.28
  - cmake=3.14.0
  - cycler=0.10.0
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - entrypoints=0.3
  - execnet=1.7.1
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - fribidi=1.0.5
  - gettext=0.19.8.1
  - glib=2.56.2
  - gmp=6.1.2
  - graphite2=1.3.13
  - graphviz=2.40.1
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - harfbuzz=1.8.8
  - icu=58.2
  - importlib_metadata=0.23
  - ipykernel=5.1.2
  - ipython=7.8.0
  - ipython_genutils=0.2.0
  - ipywidgets=7.5.1
  - isort=4.3.21
  - jedi=0.15.1
  - jinja2=2.10.1
  - jpeg=9b
  - jsonschema=3.0.2
  - jupyter=1.0.0
  - jupyter_client=5.3.3
  - jupyter_console=6.0.0
  - jupyter_core=4.5.0
  - kiwisolver=1.1.0
  - lazy-object-proxy=1.4.2
  - libblas=3.8.0
  - libcblas=3.8.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libiconv=1.15
  - liblapack=3.8.0
  - libopenblas=0.3.7
  - libpng=1.6.37
  - libprotobuf=3.9.2
  - libsodium=1.0.16
  - libtiff=4.1.0
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - make=4.2.1
  - markupsafe=1.1.1
  - matplotlib=3.1.1
  - mccabe=0.6.1
  - mistune=0.8.4
  - more-itertools=7.2.0
  - multiprocessing-logging=0.2.6
  - nbconvert=5.6.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=6.0.1
  - numpy=1.19.5
  - onnx=1.6.0
  - openblas=0.3.7
  - openssl=1.1.1d
  - packaging=19.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - pango=1.42.4
  - parso=0.5.1
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.2.0
  - pip=19.2.3
  - pixman=0.38.0
  - pluggy=0.13.0
  - prometheus_client=0.7.1
  - prompt_toolkit=2.0.9
  - protobuf=3.9.2
  - pthread-stubs=0.4
  - ptyprocess=0.6.0
  - py=1.8.0
  - pydot=1.4.1
  - pygments=2.4.2
  - pylint=2.4.2
  - pyparsing=2.4.2
  - pyqt=5.9.2
  - pyrsistent=0.15.4
  - pytest=5.2.0
  - pytest-forked=1.1.3
  - pytest-xdist=1.30.0
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.2
  - pyzmq=18.1.0
  - qt=5.9.7
  - qtconsole=4.5.5
  - readline=7.0
  - send2trash=1.5.0
  - setuptools=41.2.0
  - sip=4.19.13
  - six=1.12.0
  - sqlite=3.29.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - tornado=6.0.3
  - tqdm=4.41.1
  - traitlets=4.3.2
  - twine=3.1.1
  - typed-ast=1.4.0
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - widgetsnbextension=3.5.1
  - wrapt=1.11.2
  - xorg-libxau=1.0.9
  - xorg-libxdmcp=1.1.3
  - xz=5.2.4
  - zeromq=4.3.1
  - zipp=0.6.0
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.10
    - aenum==2.2.4
    - astor==0.8.1
    - black==19.10b0
    - cachetools==4.0.0
    - chardet==3.0.4
    - decopatch==1.4.7
    - dill==0.3.1.1
    - flatbuffers==1.12.0
    - gast==0.3.3
    - h5py==2.10.0
    - markdown==3.1.1
    - pip-autoremove==0.9.1
    - portalocker==2.0.0
    - PyYAML==5.3.1
    - scipy==1.4.1
    - setuptools_scm==4.1.2
    - tensorflow==2.4.1
    - termcolor==1.1.0
    - typing-extensions==3.7.4
    - wheel==0.35
    - -e ./xcore_interpreters
