# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: CI

on:
  push:
    branches:
      - 'develop'
  pull_request:
    branches:
      - 'develop'

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

env:
  XCORE_SDK_PATH: ${{ github.workspace }}
  XCORE_SDK_BUILDER: 'ghcr.io/xmos/xcore_sdk_builder:develop'
  XCORE_DOC_BUILDER: 'ghcr.io/xmos/doc_builder:main'

jobs:
  build_metal_examples:
    name: Build bare-metal examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Pull xcore_sdk_builder container
        run: |
          docker pull ${XCORE_SDK_BUILDER} 
      
      - name: Build
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk -e XCORE_SDK_PATH=/xcore_sdk -v ${XCORE_SDK_PATH}:/xcore_sdk ${XCORE_SDK_BUILDER} bash -l tools/ci/build_metal_examples.sh all

  build_rtos_examples:
    name: Build RTOS examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Pull xcore_sdk_builder container
        run: |
          docker pull ${XCORE_SDK_BUILDER} 
      
      - name: Build
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk -e XCORE_SDK_PATH=/xcore_sdk -v ${XCORE_SDK_PATH}:/xcore_sdk ${XCORE_SDK_BUILDER} bash -l tools/ci/build_rtos_examples.sh smoke

  build_rtos_usb_examples:
    name: Build RTOS USB examples
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Pull xcore_sdk_builder container
        run: |
          docker pull ${XCORE_SDK_BUILDER} 
      
      - name: Build
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk -e XCORE_SDK_PATH=/xcore_sdk -v ${XCORE_SDK_PATH}:/xcore_sdk ${XCORE_SDK_BUILDER} bash -l tools/ci/build_rtos_usb_examples.sh smoke

  build_rtos_tests:
    name: Build RTOS tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Pull xcore_sdk_builder container
        run: |
          docker pull ${XCORE_SDK_BUILDER} 
      
      - name: Build
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk -e XCORE_SDK_PATH=/xcore_sdk -v ${XCORE_SDK_PATH}:/xcore_sdk ${XCORE_SDK_BUILDER} bash -l tools/ci/build_rtos_tests.sh all

  test_python_install:
    name: Test Python install
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Install Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8' 

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tools/install/requirements.txt

      - name: Verify install
        run: |
          python test/verify_python_install.py

  build_documentation:
    name: Build and package documentation
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive
      
      - name: Pull doc_builder container
        run: |
          docker pull ${XCORE_DOC_BUILDER}
      
      - name: Build documentation
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk/documents -v ${{ github.workspace }}:/xcore_sdk ${XCORE_DOC_BUILDER} make clean html linkcheck SPHINXOPTS="--keep-going"
      
      - name: Save documentation artifacts
        uses: actions/upload-artifact@v2
        with:
          name: xcore_sdk_docs
          path: ./xcore_sdk/documents/_build/html
          retention-days: 5
