# YAML schema for GitHub Actions:
# https://help.github.com/en/actions/automating-your-workflow-with-github-actions/workflow-syntax-for-github-actions
#
# Helpful YAML parser to clarify YAML syntax:
# https://yaml-online-parser.appspot.com/
#
# This workflow uses actions that are not certified by GitHub. They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support documentation.
#
# This file contains the workflows that are run prior to merging a pull request.

name: HIL CI

on:
  # push:
  #   branches:
  #     - develop
  pull_request:
    branches:
      - develop

  # Allow manually triggering of the workflow.
  workflow_dispatch: {}

env:
  SDK_BUILDER_IMAGE: 'ghcr.io/xmos/sdk_app_builder:develop'

jobs:
  # JOB to run change detection
  changes:
    name: HIL change detection
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      lib_i2c: ${{ steps.filter.outputs.lib_i2c }}
      lib_i2s: ${{ steps.filter.outputs.lib_i2s }}
      lib_spi: ${{ steps.filter.outputs.lib_spi }}
      lib_uart: ${{ steps.filter.outputs.lib_uart }}
    steps:
    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          lib_i2c:
            - 'modules/hil/lib_i2c/**'
            - 'test/hil/lib_i2c/**'
          lib_i2s:
            - 'modules/hil/lib_i2s/**'
            - 'test/hil/lib_i2s/**'
          lib_spi:
            - 'modules/hil/lib_spi/**'
            - 'test/hil/lib_spi/**'
          lib_uart:
            - 'modules/hil/lib_uart/**'
            - 'test/hil/lib_uart/**'
            
  i2c_hil_tests:
    name: I2C HIL tests
    needs: changes
    if: ${{ needs.changes.outputs.lib_i2c == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Pull SDK builder image
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Run tests
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk/test/hil -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l run_tests.sh lib_i2c

  i2s_hil_tests:
    name: I2S HIL tests
    needs: changes
    if: ${{ needs.changes.outputs.lib_i2s == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Pull SDK builder image
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Run tests
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk/test/hil -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l run_tests.sh lib_i2s

  spi_hil_tests:
    name: SPI HIL tests
    needs: changes
    if: ${{ needs.changes.outputs.lib_spi == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Pull SDK builder image
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Run tests
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk/test/hil -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l run_tests.sh lib_spi


  uart_hil_tests:
    name: UART HIL tests
    needs: changes
    if: ${{ needs.changes.outputs.lib_uart == 'true' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout SDK
        uses: actions/checkout@v2
        with:
          submodules: recursive

      - name: Pull SDK builder image
        run: |
          docker pull ${SDK_BUILDER_IMAGE}

      - name: Run tests
        run: |
          docker run --user $(id -u) --rm -w /xcore_sdk/test/hil -v ${{github.workspace}}:/xcore_sdk ${SDK_BUILDER_IMAGE} bash -l run_tests.sh lib_uart
